mv main.tex preprint
mv printSWR_clean.bib preprint
mv droppedtext.tex preprint
mv 2DoList.txt preprint
mv ToDoListe.txt preprint
mv submission_stuff.txt preprint
mv img/Fig1.tex preprint
mv img/fig1concept.png preprint
mv img/Fig1.eps preprint
mv img/itool.eps preprint
mv img/3Dhex.png preprint
mv img/3Dtri.png preprint
mv img/freqMod-multi.pdf preprint
mv img/GeneralizedMaxwell.png preprint
mv img/newMWV1.pdf_tex preprint
mv img/newMWV1.pdf preprint
mv img/newMWv2.pdf preprint
mv img/newMWv2.pdf_tex preprint
mv img/newMWv3.pdf preprint
mv img/newMWv3.pdf_tex preprint
mv img/hexImg.pdf preprint
mv img/triImg.pdf preprint
mv img/ModelV2.pdf preprint
mv img/k_omega.pdf preprint
mv img/response.png preprint
mv img/discuss_sketch.PNG preprint
mv img/itoolV2.pdf_tex preprint
mv img/itoolV2.pdf preprint
mv img/illust.eps preprint
mv img/framesTri4001.png preprint
mv img/correction.pdf preprint
mv img/sizeCorr.pdf preprint
mv img/framesHex1001.png preprint
mv img/MaxwellResponse.pdf preprint
mv img/discussion.pdf preprint
mv img/framesHex1001bw.png preprint
mv img/framesTri4001bw.png preprint
mv img/triCurvV2.pdf preprint
mv img/triCurvDifference.pdf preprint
mv img/framesHex1001-4.png preprint
mv img/framesTri4001-4.png preprint
mv img/framesHex1001-5.png preprint
mv img/framesTri4001-5.png preprint
mv FDtri/Eomega.pdf preprint